version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for a static site."
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: yes

